apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: gitops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
    image: pycharmedme/backend:v2
    ports:
      - containerPort: 5000
    env:
      - name: APP_MESSAGE
        valueFrom:
          configMapKeyRef:
            name: backend-config
            key: APP_MESSAGE

